config/routes.rb
Rails.application.routes.draw do
  root :to => "questions#index"
  
   resources :questions do
    resources :answers
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question

  def upvote
    vote=self.vote.to_i
    new_vote_total = vote += 1
    self.update(:vote => new_vote_total)
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def edit
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
  end

  def update
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])

    if params[:upVoteAction] == "upvote"
      @answer.upvote
      respond_to do |format|
        format.html {redirect_to root_path}
        format.js
      end
    end
  end

  def new
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new()
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new(answer_params)

    if @answer.save
      respond_to do |format|
        format.html {redirect_to root_path}
        format.js
      end
    else
      render :new
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:answer)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    else
      render :new
    end
  end

  private

  def question_params
    params.require(:question).permit(:text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_answer.html.erb
  <div class='col-xs-6'>
    <div id="answer_<%= answer.id %>">
      <p><%= answer.answer %> <%= button_to "Vote", question_answer_path(answer.question, answer, :upVoteAction => 'upvote'), :method => 'patch', remote: true %> Tally:<span class="vote-count"><%= answer.vote %></span> <p>
    </div>
  </div>

app/views/answers/_form.html.erb
<%= form_for [@question, @answer], remote: true do |f| %>
  <%= f.label :answer %>
  <%= f.text_field :answer  %>

  <%= f.submit%>
<% end %>

app/views/answers/create.js.erb
$('#new_answer').remove();
$('#question_<%= @question.id %>').append('<%= j render(@answer) %>');
$('#question_<%= @question.id %> > #new-answer-link').show();

app/views/answers/new.js.erb
$('#question_<%= @question.id %> > #new-answer-link').hide().after('<%= j render("form") %>');

app/views/answers/update.js.erb
$("#answer_<%=@answer.id %> > .vote-count").text("<%= @answer.vote %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rather</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class='container'>
    <%= yield %>
  </div>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for @question, remote: true do |f| %>
  <%= f.label :text %>
  <%= f.text_field :text  %>

  <%= f.submit%>
<% end %>

app/views/questions/_question.html.erb
<div class= "panel panel-info">

  <div class="panel panel-title"><%= question.text %>
  </div>

  <div class="panel-body">
    <div class='row'>
      <div id="answers-container">
        <p id="add-answers">
        <div id="question_<%= question.id%>">
          <%= link_to "Add Answers", new_question_answer_path(question), remote: true, id: "new-answer-link" %></p>
          <% question.answers.order('id').each do |answer| %>
            <%= render 'answers/answer', question: question, answer: answer %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/questions/create.js.erb
$('#new_question').remove();
$('#new-question-link').show();
$('#questions-container').append('<%= j render @question %>');

app/views/questions/index.html.erb
<h1>Questions</h1>

<% @questions.each do |question| %>
  <div id="questions-container">
      <%= render question %>
  </div>
<% end %>

<%= link_to "New Question", new_question_path, remote: true, id: 'new-question-link' %>

app/views/questions/new.html.erb
<%= render 'form' %>

app/views/questions/new.js.erb
$('#new-question-link').hide().after('<%= j render("form") %>');